// let greaterthan = (8 > 9)
// greatherthan = (8 > 9)
// console.log(8 > 9);
// console.log(undefined == 0)
// console.log(10===10)
// console.log("10"===10)
console.log(null > 0)
console.log(null == 0)
console.log(null >= 0)
console.log(undefined == 0)
console.log(null > 0)
console.log(null < 0)